service: lambda-rest-api-sqlite

plugins:
  # - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'todos-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2
  # iamRoleStatements:
    # - Effect: Allow
  environment:
    TODOS_TABLE: ${self:custom.tableName}

functions:
  ielts-app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# resources:
#   Resources:
#     TodosDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: todoId
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: todoId
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.tableName}
